#!/usr/bin/env bash
# Regenerate golden fixture(s) from a real Databricks workspace.
#
# Usage:
#   fixtures/tooling/regen.sh <fixture-name>   — regenerate one fixture
#   fixtures/tooling/regen.sh --all            — regenerate unattended fixtures
#
# Requires: authenticated Databricks CLI >= 0.296.0, engine=direct.
# Local-only — never runs in CI.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GOLDEN_DIR="$SCRIPT_DIR/../golden"
INTERACTIVE_FIXTURES=(manual-drift)
# Regenerable by name, but skipped by --all: needs a workspace where classic
# compute is available (the default fixture workspace is serverless-only).
AD_HOC_FIXTURES=(wheel-bump)

is_in_fixture_list() {
  local fixture_name="$1"
  shift

  for listed_fixture in "$@"; do
    if [[ "$fixture_name" == "$listed_fixture" ]]; then
      return 0
    fi
  done

  return 1
}

is_interactive_fixture() {
  is_in_fixture_list "$1" "${INTERACTIVE_FIXTURES[@]}"
}

is_ad_hoc_fixture() {
  is_in_fixture_list "$1" "${AD_HOC_FIXTURES[@]}"
}

# Deploys and destroys call jobs/runs/delete for job_runs records, which
# rejects active runs. Deploy-triggered serverless runs can queue for minutes,
# so drain them before any step that deletes run records.
wait_for_active_runs() {
  local attempt active
  for attempt in $(seq 1 60); do
    active="$(databricks jobs list-runs --active-only -o json \
      | python3 -c 'import json, sys; print(len(json.load(sys.stdin)))')"
    if [[ "$active" == "0" ]]; then
      return 0
    fi
    echo "==> Waiting for $active active run(s) to finish..." >&2
    sleep 10
  done
  echo "Error: active runs still present after 10 minutes." >&2
  return 1
}

print_skipped_fixture_help() {
  cat >&2 <<'EOF'
Fixtures skipped by --all:
  manual-drift          Follow fixtures/golden/manual-drift/README.md.
                        It requires workspace UI edits between deploy and plan.
  wheel-bump            Needs classic compute; regenerate ad hoc via
                        `just regen wheel-bump` against a workspace that
                        allows job clusters, then `just gen-expected wheel-bump`.
EOF
}

# Source .env for BUNDLE_VAR_* overrides (gitignored, contains PII like emails).
if [[ -f "$GOLDEN_DIR/.env" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$GOLDEN_DIR/.env"
  set +a
fi

regen_one() (
  # Runs in a subshell so cd does not affect the caller.
  local name="$1"
  local fixture_dir="$GOLDEN_DIR/$name"

  if [[ "$name" == "manual-drift" ]]; then
    echo "Error: manual-drift cannot be regenerated by regen.sh." >&2
    echo "Follow fixtures/golden/manual-drift/README.md instead." >&2
    exit 2
  fi

  if [[ ! -d "$fixture_dir/before" ]]; then
    echo "Error: no before/ dir in $fixture_dir" >&2
    exit 1
  fi
  if [[ ! -d "$fixture_dir/after" ]]; then
    echo "Error: no after/ dir in $fixture_dir" >&2
    exit 1
  fi

  # Remove local state from previous runs to avoid stale references.
  rm -rf "$fixture_dir/before/.databricks" "$fixture_dir/after/.databricks"

  # Ensure we always attempt destroy, even on failure.
  # shellcheck disable=SC2329
  cleanup() {
    echo "==> [$name] Cleanup: destroying deployed state..." >&2
    wait_for_active_runs || true
    cd "$fixture_dir/after" && databricks bundle destroy --force-lock --auto-approve || true
  }
  trap cleanup EXIT

  echo "==> [$name] Deploying before/ state..."
  cd "$fixture_dir/before"
  wait_for_active_runs
  databricks bundle deploy --force-lock

  echo "==> [$name] Planning after/ state..."
  cd "$fixture_dir/after"
  databricks bundle plan -o json \
    | python3 "$SCRIPT_DIR/sanitize.py" > "$fixture_dir/plan.json.tmp"
  mv "$fixture_dir/plan.json.tmp" "$fixture_dir/plan.json"

  echo "==> [$name] Deploying after/ state..."
  cd "$fixture_dir/after"
  wait_for_active_runs
  databricks bundle deploy --force-lock --auto-approve

  echo "==> [$name] Destroying deployed state..."
  cd "$fixture_dir/after"
  wait_for_active_runs
  databricks bundle destroy --force-lock --auto-approve

  trap - EXIT
  echo "==> [$name] Done: $fixture_dir/plan.json"
)

if [[ "${1:-}" == "--all" ]]; then
  for before_dir in "$GOLDEN_DIR"/*/before; do
    [[ -d "$before_dir" ]] || continue
    name="$(basename "$(dirname "$before_dir")")"
    if is_interactive_fixture "$name"; then
      echo "==> [$name] Skipping interactive fixture."
      echo ""
      continue
    fi
    if is_ad_hoc_fixture "$name"; then
      echo "==> [$name] Skipping ad-hoc fixture (needs classic compute)."
      echo ""
      continue
    fi
    regen_one "$name"
    echo ""
  done
  echo "All unattended fixtures regenerated."
  print_skipped_fixture_help
elif [[ -n "${1:-}" ]]; then
  regen_one "$1"
else
  echo "Usage: fixtures/regen.sh <fixture-name> | --all" >&2
  exit 1
fi
